version: '3.8'
services:
  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/app/
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    volumes:
      - .:/var/app
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - web

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://root:root@db:3306/app?serverVersion=8&charset=utf8mb4
      MYSQL_DATABASE: app
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  nilm:
    image: ghcr.io/shambuwu/nilm:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: "python api.py"

volumes:
  db_data:

